---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBTkPp+qGHD+cX/ifMM2fnzqROk2s4nlKbRUuFp6P9x2N8B7ovpxO+nGjifElWNGEedtXe6k2Fsxxh6GUv33/6o2pWkPNxnM39hRVgwWlGSUEsFKZCEw1N4HTx9VM2SJVynOAy/VjhfOnZofTSA3LGSLH2zPECTLcaI9fGpOYVdzWQK/Gl61hRqh+h3jffzqQdiLmUYyxAloStRwful8ug3sndkcNwEJlGeBeDRMgxcKDMqvDw5hvlj7oa3wPXM4hl+QovExI4COb9/PlLkrVdiMnq7LgCM07dwzE2kQQARMulonLPFwn9FXmR203/Zf5r8mbZHmkLbMbPmxWD0LDIe730OItvFzWfvVW2m1vz23tLkXrBfJFhfLsGKH2OvpCc45ylR0doGh67aKInfXlUOJ6J4YsJWSJjbjUc7ezp1aEFmoRzZcUvDV+FJ4lk33aeG7JUas5Udd5JxqvhhSj7ix7TfKhFVgrshJrQveeOioS6Fk0iWpw0UcYTvhybpUHn7TqMbFVp5yMt3/JhlS3i3WTOWak4AVdoG2u5Th4AYpHgJvhj79x7L7/cRjipDbMI1crBW1f1P5IB1gE2s6pBj8keViq03gGv01Tgxbq7djaqS6qE04mJpHzsYgF6145hZQnUZBEfI6FRANiBJImRcG7/H4e7J0Cj6zK+Snta9+yM/Gp89dr35tI89SPAHBRyYg7XJJ9hUtQWQB3KEKaNd+g==
    SECRET_KEY: AgDCysiYNGxAuRqc6eDJ1HSnq3WCj4J2FOfxOib3fJ01oRClT81mI3/aNbHNfPjkIagImoM62xYMMIX1+TNqfNABn5jjPdsDLXRwB0OK0XMMg2WvtlJ1HTStwK5TIbgQVsQdVeDqHLTZCvGxK90rafuAcprcjCvH5T0H2wN7lgvHGYyfq0orACitk6HzmNVcn5ja+i17ZMCiPaXOzEzWcwe8rY+i92iGicmvw6ReYZrCY3g7DE9NAYL/KZHLM9SPxDpcTfBhnHguIMFvMZvO2C+pRWDwj7OfDWqArhx6OLUBCN4sQSX/JVX0stIYeVDXq7odRn5TPvRNEiCNXmX3ugIprcAYDR18qnlRnBBFHO5pH+jtbdJvXfyaE41scykySYibYV+A8MhAOFhEx7i48J7VBnCbf9M+vQ9wddNorw2Bua16Oo+jRpHefteNk32Pvo88RqZ0jC3dSQ+g6icrGmgv5/rgSIdkCow2NdYr+vzJgv5WLCQcDjuFfFhPaM82zULvHLVhCATZU/hojlXtjxKQ6l4mGtQvQc+hRNEvYRuiMawVKj1WdE4vcpsONn87HG4YJx5DSsAopmbVByXNXAHgJ0L/bNW8GBc5oVMFHXb//K/N9IvWlRubv6WCotyNkXezlt5CbRmpuuMhLajNixIsz1Rerodsfzf0DrgKYQhwqz7XlKGmzSpJZWUN/uc1sX8H7je0jAsj9Qu+6X0EvuDu8jsfmzQVy+LnXPEDPcvTG0mG7lM6kVUEN5qLNouaw3zNyQ==
  template:
    metadata:
      creationTimestamp: null
      name: database
      namespace: default
